### ISSUE TITLE
Sequential video in readme

### ISSUE THREAD

**Issue by ArlenCHEN** [RansML/Bayesian_Hilbert_Maps#2]
Dear authors @RansML @LydiaChan528 ,

Thanks for this open-source code. Great work!
I am wondering how did you generate the video you showed in README. It seems that data was read from intel.csv sequentially as your demo_intel.ipynb did. But demo_intel.ipynb is super slow. So I guess the video was generated by a gpu version of the demo_intel, right? I am also curious if the pytorch-cpu version could achieve the real-time performance like you showed in your video. Thanks.

**Comment by RansML** [comment]
It was actually generated on a dell notebook with the very first numpy implementation. The training time is shown just above the video (sorry, it's blurry). The training time (i.e. learning the map parameters) depends on the number of lidar hits and the number of hinge points. This is the speed-accuracy trade-off. The querying time (i.e. visualizing the map) depends on the query resolution and the number of hinge points. What you might be experiencing is the query time with a very high resolution.  
We do have have much faster versions that we have not committed yet. Feel free to email us (ransalu<at>stanford.edu).

**Comment by ArlenCHEN** [comment]
Very useful explanation. Thanks!
