### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by RansML** [RansML/Bayesian_Hilbert_Maps#3]
In the tutorial, `np.exp( -1/gammaTemp * xTemp**2 )` should be `np.exp( -gammaTemp * xTemp**2 ) `

**Comment by hahakid** [comment]
(−1.5,2)  are closer to hinge points 7, 8, 4, and 5.  should be  (-1.6,2)

**Comment by RansML** [comment]
Thanks, we'll update!
