### ISSUE TITLE
facing nan for mu

### ISSUE THREAD

**Issue by hahakid** [RansML/Bayesian_Hilbert_Maps#4]
facing nan for mu at 2nd round
![Figure_1](https://user-images.githubusercontent.com/8140299/124259036-a5cdbf80-db60-11eb-8a4e-9adecef27648.png)
I use local LiDAR data, and can generate samples as above figure, while using E-M to evaluate the mu, I always get Nan value.

**Comment by RansML** [comment]
`gamma=gamma, grid=None, cell_resolution=cell_resolution, cell_max_min=cell_max_min`

Do your parameters make sense? I'd start with something like cell_max_min=[-40,40,0,100] and cell_resolution=10.

Also, can you check how many hinge points you have? `print(model.grid.shape)`

If these are correct, then then I'd test several `gamma` values. e.g. =0.1, 10, 100. 

Alternatively, if you want to use the same parameters as in the example code, you can rescale your sampled data to be within the same range as the example.

**Comment by hahakid** [comment]
![875ac76eb8ad9edfc9a78a18e88d944](https://user-images.githubusercontent.com/8140299/124347438-6dd58380-dc17-11eb-9a99-0d4225afa2c8.png)
here is the point cloud and hinge points.
The shape is 5*5.

In the first round I can get values for mu and sig, and the second turns to Nan for both params.

Changing the gamma shows the same results. I will try sbhm.py instead.

**Comment by hahakid** [comment]
How do you preprocess the KITTI data?
I try to send pointcloud[x,y,z] into the function get_filled_txy_3d(X, y, robot_pos=np.array([**0,0,0**]), max_range=80, unoccupied_points_per_meter=0.1, margin=0.05) as **X**, and can get a similiar file formate as the two frame kitti data.

**Comment by RansML** [comment]
.
